services:
  junioronly.webapi:
    container_name: junioronly.webapi
    image: ${DOCKER_REGISTRY-}junioronlywebapi
    build:
      context: .
      dockerfile: JuniorOnly.WebAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    depends_on:
      - dev-db
    networks:
      - backend
    volumes:
      - ./JuniorOnly:/app

  dev-db:
    container_name: dev-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - db_data:/var/opt/mssql


volumes:
  db_data:

networks:
  backend:
    driver: bridge
