services:
  junioronly.webapi:
    container_name: junioronly.webapi
    image: ${DOCKER_REGISTRY-}junioronlywebapi
    build:
      context: .
      dockerfile: JuniorOnly.WebAPI/Dockerfile
    depends_on:
      - dev-db
    networks:
      - backend
    environment:
      - ConnectionStrings__Default=Server=db;Database=JuniorOnlyDB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
    volumes:
      - ./JuniorOnly:/app
    ports:
      - "5000:80"

  dev-db:
    container_name: dev-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - db_data:/var/opt/mssql


volumes:
  db_data:

networks:
  backend:
    driver: bridge
