name: api-ci
on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: 
      - "**"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore JuniorOnly.sln

    - name: Build
      run: dotnet build JuniorOnly.sln --no-restore

    - name: Run tests
      run: dotnet test JuniorOnly.sln --no-build --verbosity normal

  docker:
    runs-on: ubuntu-latest
    needs: [build-test]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit hash
        id: commit
        uses: prompt/actions-commit-hash@v3

      - name: List files
        run: ls -R

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/JuniorOnly.WebAPI/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/junioronly:${{ steps.commit.outputs.short }}
            ${{ secrets.DOCKERHUB_USERNAME }}/junioronly:latest
